name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ubuntu:
    strategy:
      matrix:
        go: [ "oldstable", "stable" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -timeout 1h ./...
  windows:
    strategy:
      matrix:
        go: [ "oldstable", "stable" ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -timeout 1h ./...
  macos:
    strategy:
      matrix:
        go: [ "oldstable", "stable" ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -timeout 1h ./...